# Generated by Django 4.1.3 on 2022-11-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="삭제여부"),
        ),
    ]
