# Generated by Django 4.1.3 on 2022-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_is_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_payment",
            field=models.BooleanField(default=True, verbose_name="지출"),
        ),
    ]
